### ISSUE TITLE
Error: requested file could not be found

### ISSUE THREAD

**Issue by evalieungh** [Between-the-Fjords/dataDownloader#4]
Hi @richardjtelford! I'm trying to download some INCLINE data, but get an error message:

> Error in `.wb_download()`:
! The requested file (8gchm) could not be found in node `zhk3m`

8gchm is the code for that specific file on OSF (osf.io/8gchm). I have updated all the dependencies of the dataDownloader package and my OSF access token should be OK (full read access token osf.full_read). Code run to encounter error:

> community <- get_file(node = "zhk3m",
                      file = "INCLINE_community_2018_2019_2021.csv",
                      path = "Data/Community", 
                      remote_path = "RawData/Community") 

More error info from rlang::last_error():

> Backtrace:
> 1. dataDownloader::get_file(...)
> 3. osfr:::osf_download.osf_tbl_file(meta_file, path = path, conflicts = conflicts)
> 4. base::Map(...)
> 5. base::mapply(FUN = f, ..., SIMPLIFY = FALSE)
> 6. osfr `<fn>`(...)
> 7. osfr:::.wb_download(...)

Any idea what the problem is? I've double checked the path names and file name and it is definitely there...

For now I'll just download it manually but it would be nice to get the code reproducible and easy to update.

**Comment by evalieungh** [comment]
Additional info: the code *does* download (or create?) a file with the correct name, but it only contains this message:

> {"message_short": "Page not found", "message_long": "The requested resource could not be found. If this should not have occurred and the issue persists, please report it to <a href=\"mailto:support@osf.io\">support@osf.io<\/a>.", "code": 404, "referrer": null}{"message_short": "Page not found", "message_long": "The requested resource could not be found. If this should not have occurred and the issue persists, please report it to <a href=\"mailto:support@osf.io\">support@osf.io<\/a>.", "code": 404, "referrer": null}

**Comment by richardjtelford** [comment]
This seems to be an issue with OSF - even the example for osfr::osf_download() does not work. Hopefully, either OSF will fix the issue or if it is permanent, osfr will be updated. There is not much I can do with dataDownloader - it very much depends on the upstream code working. If it doesn't start working in a week or so, probably worth raising an issue with OSF or osfr

**Comment by evalieungh** [comment]
OK, thanks for the reply! Ragnhild mentioned it might occur when the file is too large to be rendered in the browser. I'll check again later and email OSF if it persists.
